export const filterValues = {
  none: 'none',
  blurXs: 'blur(2px)',
  blurSm: 'blur(4px)',
  blurMd: 'blur(8px)',
  blurLg: 'blur(16px)',
  blurXl: 'blur(24px)',
  brightness90: 'brightness(0.9)',
  brightness75: 'brightness(0.75)',
  brightness110: 'brightness(1.1)',
  brightness125: 'brightness(1.25)',
  contrast125: 'contrast(1.25)',
  contrast175: 'contrast(1.75)',
  contrast200: 'contrast(2)',
  grayscale: 'grayscale(1)',
  invert: 'invert(1)',
  sepia: 'sepia(1)',
  saturate120: 'saturate(1.2)',
  hueRotate15: 'hue-rotate(15deg)',
  hueRotate90: 'hue-rotate(90deg)',
  saturate150: 'saturate(1.5)',
  dropShadowSm: 'drop-shadow(0 4px 12px rgba(15, 23, 42, 0.15))',
  dropShadowMd: 'drop-shadow(0 8px 24px rgba(15, 23, 42, 0.16))',
} as const;
export type FilterKey = keyof typeof filterValues;

export const mixBlendModeValues = [
  'normal',
  'multiply',
  'screen',
  'overlay',
  'darken',
  'lighten',
  'color-dodge',
  'color-burn',
  'hard-light',
  'soft-light',
  'difference',
  'exclusion',
  'hue',
  'saturation',
  'color',
  'luminosity',
] as const;
export type MixBlendModeKey = typeof mixBlendModeValues[number];

export const backgroundBlendModeValues = [
  'normal',
  'multiply',
  'screen',
  'overlay',
  'darken',
  'lighten',
  'color-dodge',
  'color-burn',
  'hard-light',
  'soft-light',
  'difference',
  'exclusion',
  'hue',
  'saturation',
  'color',
  'luminosity',
] as const;
export type BackgroundBlendModeKey = typeof backgroundBlendModeValues[number];
